(function() {var implementors = {};
implementors["data_encoding"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='data_encoding/enum.DecodeKind.html' title='enum data_encoding::DecodeKind'>DecodeKind</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='data_encoding/struct.DecodeError.html' title='struct data_encoding::DecodeError'>DecodeError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='data_encoding/struct.Array128.html' title='struct data_encoding::Array128'>Array128</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='data_encoding/enum.BitOrder.html' title='enum data_encoding::BitOrder'>BitOrder</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='data_encoding/struct.NoPad.html' title='struct data_encoding::NoPad'>NoPad</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='data_encoding/struct.Padded.html' title='struct data_encoding::Padded'>Padded</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='data_encoding/struct.BuilderError.html' title='struct data_encoding::BuilderError'>BuilderError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
